"""
#############################################################################
#
#   BRACKETOLOGY - AI/ML BRACKET GENERATOR
#
#   Main file to create autogenerated NCAA Tournament Bracket
#
#
#   Version:    0.1.0, 01-20-19
#
#   Nick Amell
#
#   Version History:
#   -------------------------------------------------------------------------
#   0.0.1, 12-16-18:    Initial JSON parsing/formatting w/ attributes
#   0.0.2, 01-09-19:    First non-algorithmic full pass of input to output
#   0.0.3, 01-12-19:    Successful first pass of entire framework
#   0.1.0, 01-20-19:    Version 1.0 released
#############################################################################
"""
from bracketology.data_framer import dataframe_importer, heuristic_dataframe_importer
from bracketology import bracket_builder, json_converter
from engine import PopulateBracket 

###################################################################
##      USER-DEFINED DATA CONFIGURED BELOW                       ##
###################################################################

""" Optional attributes and attribute files listed here. Examples: """
"""################################################################
Examples:
attribute_files = ['confRecords2018.csv', 'overallRecords2018.csv']
################################################################"""

attribute_files = []

""" Optional heuristics listed here """
heuristics = ["randOnRank.csv", "template.csv"]


###################################################################
###################################################################
###################################################################
##      DO NOT EDIT BELOW THIS SECTION!!! (Internal-use only)    ##
###################################################################
###################################################################
###################################################################

print("\r\nStarting...\r\n")

""" Frame any attributes """
attribute_dict = dataframe_importer(attribute_files)

""" Frame any heuristics (name of heuristic is derived from file name) """
heuristic_dict = heuristic_dataframe_importer(heuristics)

""" Generate the bracket JSON file with optional attributes """
jsonFile = json_converter.generate_json_bracket(
    "bracket_1.csv", "bracket_schema.json", attribute_dict, heuristic_dict
)

""" Bracket conversion and building """
bracket = json_converter.ConvertToBracketLists2(jsonFile)
flatBrack = bracket_builder.flat_bracket_creator(bracket)

""" Algorithms operate on flatBrack [and 'jsonFile' if 'atts' is not empty] HERE """
filledBracket = PopulateBracket(flatBrack, jsonFile)

""" Output the DAG bracket """
bracket_builder.BuildDAG(filledBracket)