"""
#############################################################################
#
#   BRACKETOLOGY - AI/ML BRACKET GENERATOR
#
#   Main file to create autogenerated NCAA Tournament Bracket
#
#
#   Version:    0.1.0, 01-20-19
#
#   Nick Amell
#
#   Version History:
#   -------------------------------------------------------------------------
#   0.0.1, 12-16-18:    Initial JSON parsing/formatting w/ attributes
#   0.0.2, 01-09-19:    First non-algorithmic full pass of input to output
#   0.0.3, 01-12-19:    Successful first pass of entire framework
#   0.1.0, 01-20-19:    Version 1.0 released
#############################################################################
"""
from bracketology import data_framer, bracket_builder, json_converter
from engine import PopulateBracket 

###################################################################
##      USER-DEFINED DATA CONFIGURED BELOW                       ##
###################################################################

""" Optional attributes and attribute files listed here. Examples: """
"""################################################################
Examples:
atts = ['confRecords', 'overallRecords']
attfiles = ['confRecords2018.csv', 'overallRecords2018.csv']
################################################################"""

atts = []
attfiles = []


""" Optional heuristics listed here """
heur = ["randOnRank.csv", "template.csv"]


###################################################################
###################################################################
###################################################################
##      DO NOT EDIT BELOW THIS SECTION!!! (Internal-use only)    ##
###################################################################
###################################################################
###################################################################

print("\r\nStarting...\r\n")

""" Frame any attributes """
attDFs = data_framer.dataframe_importer(attfiles)

""" Frame any heuristics (name of heuristic is derived from file name) """
heurDFs = data_framer.heuristic_dataframe_importer(heur)

""" Generate the bracket JSON file with optional attributes """
jsonFile = json_converter.ConvertToJSON2("bracket_1.csv", "bracket_schema.json", atts, attDFs, heur, heurDFs)

""" Bracket conversion and building """
bracket = json_converter.ConvertToBracketLists2(jsonFile)
flatBrack = bracket_builder.FlatBracketCreator(bracket)

""" Algorithms operate on flatBrack [and 'jsonFile' if 'atts' is not empty] HERE """
filledBracket = PopulateBracket(flatBrack, jsonFile)

""" Output the DAG bracket """
bracket_builder.BuildDAG(filledBracket)